version: 2

models:
  - name: dim_date_egypt
    columns:
      - name: date_id
        tests: [not_null, unique]

  - name: dim_area_egypt
    columns:
      - name: area_id
        tests: [not_null, unique]

  - name: dim_property_egypt
    columns:
      - name: property_type_id
        tests: [not_null, unique]

  - name: dim_procedure_egypt
    columns:
      - name: procedure_id
        tests: [not_null, unique]

  - name: dim_registration_egypt
    columns:
      - name: reg_type_id
        tests: [not_null, unique]

  - name: fact_transactions_egypt
    columns:
      - name: transaction_id
        tests: [not_null, unique]
      - name: date_id
        tests:
          - relationships:
              to: ref('dim_date_egypt')
              field: date_id
      - name: area_id
        tests:
          - relationships:
              to: ref('dim_area_egypt')
              field: area_id
      - name: property_type_id
        tests:
          - relationships:
              to: ref('dim_property_egypt')
              field: property_type_id
      - name: procedure_id
        tests:
          - relationships:
              to: ref('dim_procedure_egypt')
              field: procedure_id
      - name: reg_type_id
        tests:
          - relationships:
              to: ref('dim_registration_egypt')
              field: reg_type_id