services:
  - type: web
    name: smartmove-backend
    env: docker
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.render
      - key: PYTHON_VERSION
        value: "3.12.0"
