# Generated by Django 5.2.13 on 2026-06-13 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_role', models.CharField(blank=True, max_length=50)),
                ('target_region', models.CharField(blank=True, max_length=50)),
                ('recipient_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Log',
                'verbose_name_plural': 'Broadcast Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_notifications', models.BooleanField(default=True)),
                ('report_notifications', models.BooleanField(default=True)),
                ('security_notifications', models.BooleanField(default=True)),
                ('admin_broadcasts', models.BooleanField(default=True)),
                ('cloud_notifications', models.BooleanField(default=True)),
                ('subscription_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('system', 'System'), ('data', 'Data'), ('ai', 'AI'), ('security', 'Security'), ('admin', 'Admin Broadcast'), ('subscription', 'Subscription'), ('report', 'Report'), ('cloud', 'Cloud')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('icon', models.CharField(blank=True, default='', help_text="e.g. 'upload', 'report', 'security', 'warning'", max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', help_text="Optional deep-link path, e.g. '/cloud'", max_length=512)),
                ('actions', models.JSONField(blank=True, default=list, help_text="List of action buttons, e.g. [{'label': 'View Report', 'url': '...'}]")),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('source_app', models.CharField(blank=True, default='', help_text="e.g. 'agentic_ai', 'smartmove_cloud', 'admin_broadcast'", max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Time after which notification automatically disappears', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The recipient of this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx')],
            },
        ),
    ]
