# Generated by Django 5.2.12 on 2026-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfHealingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(db_index=True, help_text='The alertname label from the Alertmanager payload.', max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='warning', max_length=20)),
                ('runbook_name', models.CharField(help_text='Python function name from runbooks.py that was invoked.', max_length=255)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='triggered', max_length=20)),
                ('result_message', models.TextField(blank=True, default='', help_text='Stdout/stderr or summary returned by the runbook.')),
                ('alert_payload', models.JSONField(blank=True, default=dict, help_text='Full JSON payload received from Alertmanager.')),
                ('service', models.CharField(blank=True, db_index=True, default='', help_text='The service label from the alert (e.g. backend, celery, redis).', max_length=100)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Self-Healing Log',
                'verbose_name_plural': 'Self-Healing Logs',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['alert_name', 'severity', '-triggered_at'], name='idx_alert_severity_time')],
            },
        ),
    ]
