# Generated by Django 5.2.15 on 2026-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_pro_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisworkspace',
            name='dashboard_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
