# Generated by Django 5.2.12 on 2026-05-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_currency_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency_preference',
            field=models.CharField(default='USD', help_text="The user's preferred fiat currency for dashboard and chatbot conversions.", max_length=3),
        ),
    ]
