# Generated by Django 5.2.12 on 2026-05-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('users', '0003_alter_user_currency_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency_preference',
            field=models.ForeignKey(blank=True, help_text="The user's preferred fiat currency for dashboard and chatbot conversions.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currencyrate'),
        ),
    ]
