# Generated by Django 5.2.12 on 2026-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_currency_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('egypt', 'Egypt'), ('dubai', 'Dubai'), ('england', 'England')], max_length=10, null=True),
        ),
    ]
