# Generated by Django 5.2.12 on 2026-04-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('verify_email', 'Verify Email'), ('reset_password', 'Reset Password'), ('change_password', 'Change Password'), ('change_email', 'Change Email')], max_length=20),
        ),
    ]
