# Generated by Django 5.2.13 on 2026-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('england', 'England'), ('dubai', 'Dubai'), ('egypt', 'Egypt')], max_length=20)),
                ('source', models.CharField(choices=[('local', 'Local Upload'), ('google', 'Google Drive'), ('microsoft', 'Microsoft 365')], default='local', max_length=20)),
                ('azure_blob_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VALIDATED', 'Validated'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('FAILED', 'Failed'), ('FAILED_SCHEMA_DRIFT', 'Failed: Schema Drift'), ('FAILED_INTERRUPTED', 'Failed: Interrupted (Zombie)'), ('CANCELED', 'Canceled')], default='PENDING', max_length=30)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('error_reason', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
