# Generated by Django 5.2.12 on 2026-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimport',
            name='celery_task_id',
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='status',
            field=models.CharField(choices=[('PENDING_VIRUS_SCAN', 'Pending Virus Scan'), ('FAILED_SECURITY_QUARANTINE', 'Failed: Security Quarantine'), ('PROCESSING_ETL', 'Processing (ETL)'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('COMPLETED', 'Completed')], default='PENDING_VIRUS_SCAN', max_length=30),
        ),
        migrations.DeleteModel(
            name='FailedDataRow',
        ),
    ]
