# Generated by Django 5.2.12 on 2026-06-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('role', models.CharField(choices=[('user', 'User (Free)'), ('data_analyst', 'Data Analyst (Premium)')], default='user', max_length=20)),
                ('additional_storage_gb', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('data_analyst_tier', 'Data Analyst Main Upgrade'), ('premium_bundle', 'Premium Data Analyst Bundle'), ('mail_egypt', 'Egypt Report Mailing'), ('mail_dubai', 'Dubai Report Mailing'), ('mail_uk', 'UK Report Mailing'), ('mail_all_regions', 'All Regions Report Bundle'), ('storage_expansion', 'Storage Expansion Add-on')], max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'), models.Index(fields=['plan_type', 'status'], name='subscriptio_plan_ty_26d4ac_idx')],
            },
        ),
    ]
