# Generated by Django 5.2.12 on 2026-06-12 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='stripe_customer_id',
            new_name='ls_customer_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='ls_subscription_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_price_id',
            new_name='ls_variant_id',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ls_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
