# Generated by Django 5.2.13 on 2026-06-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_stripe_customer_id_customerprofile_ls_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('analyst', 'Analyst Plan'), ('analyst_pro_max', 'Analyst Pro Max Plan'), ('storage_per_gb', 'Storage Per GB'), ('storage_5gb', 'Storage 5GB Bundle'), ('storage_9gb', 'Storage 9GB Bundle'), ('report_single_egypt', 'Egypt Report Mailing'), ('report_single_dubai', 'Dubai Report Mailing'), ('report_single_england', 'England Report Mailing'), ('report_all', 'All Regions Report Bundle')], max_length=50),
        ),
    ]
