# Generated by Django 5.2.12 on 2026-04-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('currency_code', models.CharField(help_text='ISO 4217 currency code (e.g. EUR, GBP, JPY).', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('rate_to_usd', models.DecimalField(decimal_places=6, help_text='How many units of this currency equal 1 USD.', max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent oracle consensus update.')),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['currency_code'],
            },
        ),
    ]
