"""
SmartMove — LLM Client (Anthropic Claude)

Production implementation using the ``anthropic`` Python SDK to generate
executive summary reports via Claude 3.5 Sonnet.

Environment:
    ANTHROPIC_API_KEY  — Required.  Set in .env or Airflow Variables.

Usage:
    from utils.llm_client import get_executive_summary

    markdown = get_executive_summary(rendered_prompt)
"""

from __future__ import annotations

import logging
import os

import anthropic

logger = logging.getLogger(__name__)

# ── Configuration ────────────────────────────────────────────────────────────
MODEL = "claude-sonnet-4-6"
MAX_TOKENS = 4096
TEMPERATURE = 0.2  # Low temperature for strict, consistent report formatting


def get_executive_summary(prompt_text: str) -> str:
    """
    Send a rendered executive-summary prompt to Claude and return the
    Markdown analysis.

    Parameters
    ----------
    prompt_text : str
        The fully rendered Jinja template with all market data substituted.

    Returns
    -------
    str
        Markdown-formatted executive summary generated by the LLM.

    Raises
    ------
    anthropic.AuthenticationError
        If ``ANTHROPIC_API_KEY`` is invalid or missing.
    anthropic.APIError
        For any upstream API failure (rate limits, server errors, etc.).
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY environment variable is not set. "
            "Configure it in .env or Airflow Variables before running "
            "the report pipeline."
        )

    client = anthropic.Anthropic(api_key=api_key)

    logger.info(
        "Calling Anthropic API: model=%s, max_tokens=%d, temperature=%.1f",
        MODEL,
        MAX_TOKENS,
        TEMPERATURE,
    )

    message = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE,
        messages=[
            {
                "role": "user",
                "content": prompt_text,
            }
        ],
        system=(
            "You are SmartMove AI, a world-class real-estate analytics engine. "
            "You produce authoritative, data-driven executive summaries for "
            "institutional investors. Always respond in well-structured Markdown. "
            "Never fabricate data points that were not provided in the prompt."
        ),
    )

    # Extract text from the response content blocks
    response_text = ""
    for block in message.content:
        if block.type == "text":
            response_text += block.text

    logger.info(
        "Anthropic API response received: %d chars, stop_reason=%s",
        len(response_text),
        message.stop_reason,
    )

    return response_text
