# Generated by Django 5.2.12 on 2026-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmove_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
