# Generated by Django 5.2.15 on 2026-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartmove_cloud', '0002_userfile_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='minio_object_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
