# Generated by Django 5.2.12 on 2026-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='scopes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
