"""
SmartMove Reports — Report Model

Stores metadata for monthly executive-summary PDF reports generated by the
Airflow pipeline.  One report per region per month is enforced via a composite
unique constraint.

The ``age_months`` property drives the tiered paywall logic in the serializer
layer (see ``serializers.py``).
"""

from django.db import models
from django.utils import timezone


class Report(models.Model):
    """Monthly executive-summary report for a single region."""

    # ── Explicit manager (Pyright compliance, project convention) ──────────
    objects = models.Manager()

    # ── Region choices — mirrors apps.users.models.User.Region ────────────
    class Region(models.TextChoices):
        EGYPT   = 'egypt',   'Egypt'
        DUBAI   = 'dubai',   'Dubai'
        ENGLAND = 'england', 'England'

    # ── Core fields ───────────────────────────────────────────────────────
    region = models.CharField(
        max_length=10,
        choices=Region.choices,
        help_text="The geographic market this report covers.",
    )
    report_month = models.PositiveSmallIntegerField(
        help_text="Month of the reporting period (1-12).",
    )
    report_year = models.PositiveSmallIntegerField(
        help_text="Year of the reporting period (e.g. 2026).",
    )
    title = models.CharField(
        max_length=255,
        help_text="Human-readable report title shown in the UI.",
    )

    # ── Storage ───────────────────────────────────────────────────────────
    azure_blob_url = models.URLField(
        max_length=1024,
        help_text="Full URL to the generated PDF in Azure Blob Storage.",
        null=True, blank=True,
    )
    pdf_file = models.FileField(
        upload_to='reports/temp/',
        null=True,
        blank=True,
        help_text="Temporary local storage for the generated PDF before Azure upload.",
    )
    file_size_bytes = models.PositiveBigIntegerField(
        default=0,
        help_text="PDF file size for UI display (e.g. '2.4 MB').",
    )

    # ── Metadata ──────────────────────────────────────────────────────────
    generated_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when the PDF was generated.",
    )
    is_published = models.BooleanField(
        default=True,
        help_text="Admin toggle — unpublished reports are hidden from all users.",
    )

    class Meta:
        ordering = ['-report_year', '-report_month']
        constraints = [
            models.UniqueConstraint(
                fields=['region', 'report_month', 'report_year'],
                name='unique_report_per_region_per_month',
            ),
        ]
        verbose_name = 'Report'
        verbose_name_plural = 'Reports'

    def __str__(self) -> str:
        return f"{self.get_region_display()} — {self.report_month:02d}/{self.report_year}"

    # ── Paywall helper ────────────────────────────────────────────────────
    @property
    def age_months(self) -> int:
        """
        Number of whole months between the report period and the current date.

        Used by the serializer / view layer to enforce the tiered paywall:
            0-2 months  → can_view + can_download
            2-6 months  → can_view only
            6+  months  → 403 Forbidden (for non-analyst users)
        """
        now = timezone.now()
        return (now.year - int(str(self.report_year))) * 12 + (now.month - int(str(self.report_month)))


class ReportActivityLog(models.Model):
    """Audit log tracking report views and downloads."""
    objects = models.Manager()

    class Action(models.TextChoices):
        VIEW     = 'VIEW',     'View'
        DOWNLOAD = 'DOWNLOAD', 'Download'

    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        related_name='report_activity_logs',
    )
    report = models.ForeignKey(
        Report,
        on_delete=models.CASCADE,
        related_name='activity_logs',
    )
    action = models.CharField(max_length=10, choices=Action.choices)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']
        verbose_name = 'Report Activity Log'
        verbose_name_plural = 'Report Activity Logs'

    def __str__(self) -> str:
        return f"{self.user} {self.action} {self.report} at {self.timestamp}"


class RegionalPipelineStatus(models.Model):
    """Tracks the success or failure of regional Airflow pipelines."""

    objects = models.Manager()

    region = models.CharField(
        max_length=10,
        choices=Report.Region.choices,
        help_text="The geographic market.",
        unique=True,
    )
    status = models.CharField(
        max_length=50,
        help_text="Status of the pipeline (e.g., SUCCESS, FAILED, RUNNING).",
    )
    last_updated = models.DateTimeField(
        auto_now=True,
        help_text="Timestamp of the last status update.",
    )

    class Meta:
        ordering = ['region']
        verbose_name = 'Regional Pipeline Status'
        verbose_name_plural = 'Regional Pipeline Statuses'

    def __str__(self) -> str:
        return f"{self.get_region_display()} — {self.status} at {self.last_updated}"
