# infrastructure/ansible/inventory.ini

[control_plane]
server1_app ansible_host=100.106.181.56

[k3s_workers]
server2_support ansible_host=100.111.232.64  # <--- Added to handle the 60% traffic overflow

[database_nodes]
server2_support ansible_host=100.111.232.64   # <--- Retains its role as the data fortress

[command_center]
server3_security ansible_host=100.99.164.119

[engine_nodes]
server4_engine ansible_host=100.68.143.34

#[bastion_nodes]
#vm1_bastion ansible_host=100.x.x.x

##[utility_nodes]
#vm2_log_forwarder ansible_host=100.x.x.x
#vm3_watchdog ansible_host=100.x.x.x
#vm7_image_optimizer ansible_host=100.x.x.x

##[cache_nodes]
#vm4_tempo_cache ansible_host=100.x.x.x
#vm5_mimir_cache ansible_host=100.x.x.x
#vm6_loki_cache ansible_host=100.x.x.x

#[spare_nodes]
#vm8_hot_spare ansible_host=100.x.x.x

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=./ssh_keys/id_rsa_azure
ansible_become=yes
ansible_become_method=sudo# infrastructure/ansible/inventory.ini

[control_plane]
server1_app ansible_host=100.106.181.56

[k3s_workers]
server2_support ansible_host=100.111.232.64   # <--- Added to handle the 60% traffic overflow

[database_nodes]
server2_support ansible_host=100.111.232.64   # <--- Retains its role as the data fortress

[command_center]
server3_security ansible_host=100.99.164.119

[engine_nodes]
server4_engine ansible_host=100.68.143.34

#[bastion_nodes]
#vm1_bastion ansible_host=100.x.x.x

#[utility_nodes]
#vm2_log_forwarder ansible_host=100.x.x.x
#vm3_watchdog ansible_host=100.x.x.x
#vm7_image_optimizer ansible_host=100.x.x.x

#[cache_nodes]
#vm4_tempo_cache ansible_host=100.x.x.x
#vm5_mimir_cache ansible_host=100.x.x.x
#vm6_loki_cache ansible_host=100.x.x.x

#[spare_nodes]
#vm8_hot_spare ansible_host=100.x.x.x

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=./ssh_keys/id_rsa_azure
ansible_become=yes
ansible_become_method=sudo