# Generated by Django 5.2.14 on 2026-05-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('egypt', 'Egypt'), ('dubai', 'Dubai'), ('england', 'England')], help_text='The geographic market this report covers.', max_length=10)),
                ('report_month', models.PositiveSmallIntegerField(help_text='Month of the reporting period (1-12).')),
                ('report_year', models.PositiveSmallIntegerField(help_text='Year of the reporting period (e.g. 2026).')),
                ('title', models.CharField(help_text='Human-readable report title shown in the UI.', max_length=255)),
                ('azure_blob_url', models.URLField(help_text='Full URL to the generated PDF in Azure Blob Storage.', max_length=1024)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, help_text="PDF file size for UI display (e.g. '2.4 MB').")),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the PDF was generated.')),
                ('is_published', models.BooleanField(default=True, help_text='Admin toggle — unpublished reports are hidden from all users.')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-report_year', '-report_month'],
                'constraints': [models.UniqueConstraint(fields=('region', 'report_month', 'report_year'), name='unique_report_per_region_per_month')],
            },
        ),
    ]
