# Generated by Django 5.2.12 on 2026-06-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalPipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('egypt', 'Egypt'), ('dubai', 'Dubai'), ('england', 'England')], help_text='The geographic market.', max_length=10, unique=True)),
                ('status', models.CharField(help_text='Status of the pipeline (e.g., SUCCESS, FAILED, RUNNING).', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the last status update.')),
            ],
            options={
                'verbose_name': 'Regional Pipeline Status',
                'verbose_name_plural': 'Regional Pipeline Statuses',
                'ordering': ['region'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Temporary local storage for the generated PDF before Azure upload.', null=True, upload_to='reports/temp/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='azure_blob_url',
            field=models.URLField(blank=True, help_text='Full URL to the generated PDF in Azure Blob Storage.', max_length=1024, null=True),
        ),
    ]
