smartmove_england:
  target: prod
  outputs:
    prod:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: "{{ env_var('AZURE_SQL_HOST') }}"
      port: 1433
      database: "{{ env_var('AZURE_SQL_DB_NAME') }}"
      schema: dbo
      user: "{{ env_var('AZURE_SQL_USER') }}"
      password: "{{ env_var('AZURE_SQL_PASSWORD') }}"
      encrypt: true
      trust_cert: true
