# Generated by Django 5.2.12 on 2026-05-08 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_currency_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chatbot_quota', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('queries_used_today', models.PositiveIntegerField(default=0)),
                ('max_queries_per_day', models.PositiveIntegerField(default=5, help_text='Maximum allowed queries per calendar day.')),
                ('last_reset', models.DateField(default=django.utils.timezone.now, help_text='Date when the counter was last zeroed.')),
            ],
            options={
                'verbose_name': 'User Quota',
                'verbose_name_plural': 'User Quotas',
            },
        ),
        migrations.CreateModel(
            name='ConversationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='WebSocket channel name or session UUID.', max_length=64)),
                ('prompt', models.TextField(help_text="User's raw input text.")),
                ('response', models.TextField(help_text="Agent's final response text.")),
                ('model_used', models.CharField(blank=True, default='', help_text='e.g. gemini-2.0-flash, gpt-4o', max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='End-to-end latency in milliseconds.')),
                ('tools_invoked', models.JSONField(blank=True, default=list, help_text='List of tool names that were called during the turn.')),
                ('cache_hit', models.BooleanField(default=False, help_text='True if the response was served from semantic cache.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Audit Log',
                'verbose_name_plural': 'Conversation Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='chatbot_con_user_id_06e8d2_idx'), models.Index(fields=['session_id', '-created_at'], name='chatbot_con_session_c086d0_idx')],
            },
        ),
    ]
